calendar:
  subjects:
    - "Projektni seminar PRIN"
    - "Računalniški raziskovalni seminar"
    - "Seminar (PBI)"
  exclude:
    - "Matematični praktikum EN"
  calendarURLs:
    - "https://www.wise-tt.com/wtt_up_famnit/index.jsp?filterId=0;20,65,89;0;0;"
    - "https://www.wise-tt.com/wtt_up_famnit/index.jsp?filterId=0;47,108,185,187,111,181;0;0;"
