calendar:
  subjects:
    - "Matematični praktikum"
    - "Računalniški raziskovalni seminar"
    - "Podatkovno inženirstvo in distribuirani informacijski sistemi"
  exclude:
    - "Matematični praktikum EN"
  calendarURLs:
    - "https://www.wise-tt.com/wtt_up_famnit/index.jsp?filterId=0;79,39,40,148,149,76,77,73,72;0;0;"
