calendar:
  subjects:
    - 'Projektni seminar PRIN'
    - 'Verjetnost in statistika v tehniki in naravoslovju'
    - 'Računalniški raziskovalni seminar'
    - 'Inteligentni sistemi'
    - 'Računalniške družbene vede'
    - 'Izbrana poglavja iz vizualizacije podatkov'
  calendarURLs:
    - 'https://www.wise-tt.com/wtt_up_famnit/index.jsp?filterId=0;52,82;0;0;'
