name: Docker publish image

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/**'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN_GHCR }}
      - name: build and push
        run: |
          docker build . -t ghcr.io/andrejerjavec/calendar-sync:latest
          docker push ghcr.io/andrejerjavec/calendar-sync:latest
